/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.das6t.component;

/**
 *
 * @author Daniel Aldana(DaS6T)
 */

import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import java.awt.Color;
import java.awt.Font;
import net.miginfocom.swing.MigLayout;
import com.das6t.event.EventMenu;
import java.util.ArrayList;
import com.das6t.swing.ButtonHeaderMenu;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class HeaderMenu extends javax.swing.JPanel {
    
    Font robotoPlain = new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13);
    Font robotoBold = new Font(FlatRobotoFont.FAMILY, Font.BOLD, 18);
    Color fontColor = new Color(153,153,153);
    
    private EventMenu evt;

    /**
     * Creates new form HeaderMenu
     */
    public HeaderMenu() {
        initComponents();
        panelHeaderMenu.setLayout(new MigLayout("filly, inset 5", "[fill]", "[][grow][]"));
        this.setOpaque(false);
        lblTitulo.setForeground(fontColor);
    }
    
    public void initHeaderMenu(EventMenu evt, ArrayList<ButtonHeaderMenu>buttons){
        this.evt = evt;
        int index = 0;
        for(ButtonHeaderMenu bt:buttons) {
            addHeaderMenu(bt,index);
            index++;
        }
    }
    
    private void addHeaderMenu(ButtonHeaderMenu button, int index){
        panelHeaderMenu.add(button);
        button.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ev) {
                evt.selected(index);
                setSelected(button);
            }
        });
    }
    
    private void setSelected(ButtonHeaderMenu button){
        for(Component comp:panelHeaderMenu.getComponents()) {
            if(comp instanceof ButtonHeaderMenu) {
                ButtonHeaderMenu bt = (ButtonHeaderMenu)comp;
                bt.setSelected(false);
            }
        }
        button.setSelected(true);
    }
    
    public void setViewName(String name){
        lblTitulo.setText(name);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        semiRoundedPanel1 = new com.das6t.swing.SemiRoundedPanel();
        lblTitulo = new javax.swing.JLabel();
        panelHeaderMenu = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(936, 45));
        setMinimumSize(new java.awt.Dimension(936, 45));
        setPreferredSize(new java.awt.Dimension(936, 45));

        semiRoundedPanel1.setMaximumSize(new java.awt.Dimension(936, 45));
        semiRoundedPanel1.setMinimumSize(new java.awt.Dimension(936, 45));

        lblTitulo.setFont(robotoBold);
        lblTitulo.setText("Vista");
        lblTitulo.setMaximumSize(new java.awt.Dimension(150, 24));
        lblTitulo.setMinimumSize(new java.awt.Dimension(150, 24));
        lblTitulo.setPreferredSize(new java.awt.Dimension(150, 24));

        panelHeaderMenu.setBackground(new java.awt.Color(61, 61, 61));

        javax.swing.GroupLayout panelHeaderMenuLayout = new javax.swing.GroupLayout(panelHeaderMenu);
        panelHeaderMenu.setLayout(panelHeaderMenuLayout);
        panelHeaderMenuLayout.setHorizontalGroup(
            panelHeaderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 748, Short.MAX_VALUE)
        );
        panelHeaderMenuLayout.setVerticalGroup(
            panelHeaderMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout semiRoundedPanel1Layout = new javax.swing.GroupLayout(semiRoundedPanel1);
        semiRoundedPanel1.setLayout(semiRoundedPanel1Layout);
        semiRoundedPanel1Layout.setHorizontalGroup(
            semiRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semiRoundedPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelHeaderMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        semiRoundedPanel1Layout.setVerticalGroup(
            semiRoundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(semiRoundedPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
            .addComponent(panelHeaderMenu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semiRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(semiRoundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelHeaderMenu;
    private com.das6t.swing.SemiRoundedPanel semiRoundedPanel1;
    // End of variables declaration//GEN-END:variables
}
