/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vistas;

import com.das6t.swing.ButtonHeaderMenu;
import com.das6t.event.EventMenu;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JInternalFrame;
import servicios.DashboardServicio;
import servicios.ReservacionServicio;
import javax.swing.table.DefaultTableModel;
import servicios.ReservacionServicio;

/**
 *
 * @author Daniel Aldana(DaS6T)
 */
public class DashboardVista extends javax.swing.JPanel {
    
    private ArrayList<ButtonHeaderMenu> buttons = new ArrayList<>();
    private List<ReservacionServicio> reservas;
    private DefaultTableModel modeloTabla;

    /**
     * Creates new form NewJPanel
     */
    public DashboardVista() {
        initComponents();
        this.setOpaque(false);
        
        modeloTabla = (DefaultTableModel)tblReservas.getModel();
        
        habDisponibles.setBackgroundRounded(new Color(61,61,61));
        habDisponibles.setTitulo("Habitaciones disponibles");
        habDisponibles.setDato(String.valueOf(DashboardServicio.habitacionesDisponibles()));
        habOcupadas.setBackgroundRounded(new Color(61,61,61));
        habOcupadas.setTitulo("Habitaciones ocupadas");
        habOcupadas.setDato(String.valueOf(DashboardServicio.habitacionesOcupadas()));
        habMantenimiento.setBackgroundRounded(new Color(61,61,61));
        habMantenimiento.setTitulo("Habitaciones en mantenimiento");
        habMantenimiento.setDato(String.valueOf(DashboardServicio.habitacionesEnMantenimiento()));
        
        EventMenu evt = new EventMenu() {
            @Override
            public void selected(int index) {
                switch(index){
                    case 0:
                        break;
                    case 1:
                        break;
                }
            }
        };
        headerMenu.initHeaderMenu(evt, buttons);
        headerMenu.setViewName("Dashboard"); //escriba aqui el nombre de la vista por 
        llenarTabla();
    }
    
    public void llenarTabla() {
        reservas = DashboardServicio.reservasActivas();
        for(ReservacionServicio reserva:reservas) {
            modeloTabla.addRow(new Object[] {
                reserva.getNumHab(),
                reserva.getNomCliente(),
                reserva.getFechaIngreso(),
                reserva.getFechaSalida()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new com.das6t.swing.RoundedPanel();
        headerMenu = new com.das6t.component.HeaderMenu();
        jDesktopPane = new javax.swing.JDesktopPane();
        habDisponibles = new com.das6t.component.InfoComponent();
        habOcupadas = new com.das6t.component.InfoComponent();
        habMantenimiento = new com.das6t.component.InfoComponent();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblReservas = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(936, 690));
        setMinimumSize(new java.awt.Dimension(936, 690));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(936, 690));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setBackground(new java.awt.Color(45, 42, 46));
        roundedPanel1.setMaximumSize(new java.awt.Dimension(936, 690));
        roundedPanel1.setMinimumSize(new java.awt.Dimension(936, 690));
        roundedPanel1.setPreferredSize(new java.awt.Dimension(936, 690));

        jDesktopPane.setOpaque(false);

        tblReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No. Habitacion", "Cliente", "Fecha ingreso", "Fecha salida"
            }
        ));
        jScrollPane1.setViewportView(tblReservas);

        jDesktopPane.setLayer(habDisponibles, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(habOcupadas, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(habMantenimiento, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jDesktopPaneLayout.createSequentialGroup()
                        .addComponent(habDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(habOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(habMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(habDisponibles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(habMantenimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 940, Short.MAX_VALUE)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jDesktopPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addComponent(headerMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jDesktopPane)
                .addContainerGap())
        );

        add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 690));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.das6t.component.InfoComponent habDisponibles;
    private com.das6t.component.InfoComponent habMantenimiento;
    private com.das6t.component.InfoComponent habOcupadas;
    private com.das6t.component.HeaderMenu headerMenu;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JScrollPane jScrollPane1;
    private com.das6t.swing.RoundedPanel roundedPanel1;
    private javax.swing.JTable tblReservas;
    // End of variables declaration//GEN-END:variables
}
