/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import com.formdev.flatlaf.extras.FlatSVGIcon;
import static java.lang.Integer.parseInt;
import java.util.List;
import javax.swing.JOptionPane;
import servicios.TipoHabitacionServicio;
import servicios.EstadoHabitacionServicio;
import servicios.HabitacionServicio;
import java.sql.SQLException;
import javax.naming.NamingException;
import javax.swing.ImageIcon;
import vistas.HabitacionesVista;

/**
 *
 * @author Salvador Hernández
 */
public class HabitacionesVista_Editar extends javax.swing.JInternalFrame {

    private HabitacionesVista habitacionesVista;
    private String noHabitacion;
    private String tipoHabitacion;
    private String estadoHabitacion;

    public HabitacionesVista_Editar(HabitacionesVista habitacionesVista, String noHabitacion, String tipoHabitacion, String estadoHabitacion) {

        initComponents();
        this.habitacionesVista = habitacionesVista;
        this.noHabitacion = noHabitacion;
        this.tipoHabitacion = tipoHabitacion;
        this.estadoHabitacion = estadoHabitacion;

        txtNoHabitacion.setText(noHabitacion);

        ImageIcon iconoEliminar = new FlatSVGIcon("com/das6t/icons/delete_ivan.svg", 16, 16);
        btnEliminar.setIcon(iconoEliminar);

        txtNoHabitacion.requestFocus();

        try {
            List<TipoHabitacionServicio> tiposHabitaciones = TipoHabitacionServicio.visualizarTipo();

            selectTipoHabitacion.removeAllItems();
            selectTipoHabitacion.addItem("Selecciona un tipo de habitación");

            for (TipoHabitacionServicio habitacion : tiposHabitaciones) {
                selectTipoHabitacion.addItem(habitacion.getTipoHab());
            }

            for (int i = 0; i < selectTipoHabitacion.getItemCount(); i++) {
                String item = (String) selectTipoHabitacion.getItemAt(i);
                if (item.equals(tipoHabitacion)) {
                    selectTipoHabitacion.setSelectedIndex(i);
                    break;
                }
            }

        } catch (SQLException | NamingException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener los tipos de habitaciones.");
        }

        try {
            List<EstadoHabitacionServicio> estadoHabitaciones = EstadoHabitacionServicio.obtenerTodosLosEstados();

            selectEstadoDeHabitacion.removeAllItems();
            selectEstadoDeHabitacion.addItem("Selecciona un estado de habitación");

            for (EstadoHabitacionServicio stHabitacion : estadoHabitaciones) {
                selectEstadoDeHabitacion.addItem(stHabitacion.getDetalle_estado());
            }

            for (int i = 0; i < selectEstadoDeHabitacion.getItemCount(); i++) {
                String item = (String) selectEstadoDeHabitacion.getItemAt(i);
                if (item.equals(estadoHabitacion)) {
                    selectEstadoDeHabitacion.setSelectedIndex(i);
                    break;
                }
            }

        } catch (SQLException | NamingException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al obtener los estados de habitaciones.");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        selectTipoHabitacion = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        selectEstadoDeHabitacion = new javax.swing.JComboBox<>();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        txtNoHabitacion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        btnEliminar = new javax.swing.JButton();

        setMaximumSize(new java.awt.Dimension(916, 629));
        setMinimumSize(new java.awt.Dimension(916, 629));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Editar Habitación");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel2.setText("Tipo de Habitación");

        selectTipoHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel3.setText("Estado de Habitación");

        selectEstadoDeHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        txtNoHabitacion.setEditable(false);
        txtNoHabitacion.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNoHabitacion.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        txtNoHabitacion.setEnabled(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel4.setText("No de Habitación");

        btnEliminar.setText(" Eliminar");
        btnEliminar.setFocusable(false);
        btnEliminar.setPreferredSize(new java.awt.Dimension(27, 27));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(576, 576, 576)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancelar)
                                .addGap(18, 18, 18)
                                .addComponent(btnGuardar))
                            .addComponent(selectEstadoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtNoHabitacion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectTipoHabitacion, javax.swing.GroupLayout.Alignment.LEADING, 0, 312, Short.MAX_VALUE))
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 844, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(selectEstadoDeHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            int id = parseInt(txtNoHabitacion.getText());
            int iTipoHabi = selectTipoHabitacion.getSelectedIndex();
            int iEstaHabi = selectEstadoDeHabitacion.getSelectedIndex();

            if (iTipoHabi == 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un Tipo de Habitacion.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (iEstaHabi == 0) {
                JOptionPane.showMessageDialog(this, "Selecciona un Estado de Habitacion.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            if (HabitacionServicio.modificarHabitacion(id, iTipoHabi, iEstaHabi)) {

                JOptionPane.showMessageDialog(this, "Habitacion actualizada exitosamente", "Éxito", JOptionPane.INFORMATION_MESSAGE);

                habitacionesVista.abrirInicio();

            } else {
                JOptionPane.showMessageDialog(this, "No fue posible actualizar la habitación, consulta con tu administrador de sistemas", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error, muesta este mensaje a tu administrador de sistemas: " + ex, "Error", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        habitacionesVista.abrirInicio();
    }//GEN-LAST:event_btnCancelarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JComboBox<String> selectEstadoDeHabitacion;
    private javax.swing.JComboBox<String> selectTipoHabitacion;
    private javax.swing.JTextField txtNoHabitacion;
    // End of variables declaration//GEN-END:variables
}
