/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Daniel Aldana
 */

import javax.swing.table.DefaultTableModel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.JLabel;
import java.util.List;
import javax.swing.JOptionPane;
import servicios.Usuarios;

public class TablaUsuarios extends javax.swing.JInternalFrame {
    
    DefaultTableModel modeloTabla;
    List<Usuarios> tableData;
    DefaultTableCellRenderer render = new DefaultTableCellRenderer();
    private UsuariosVista usuariosVista;

    /**
     * Creates new form TablaUsuarios
     */
    public TablaUsuarios(UsuariosVista usuariosVista) {
        initComponents();
        this.usuariosVista = usuariosVista;
        
        render.setHorizontalAlignment(JLabel.CENTER);
        modeloTabla = (DefaultTableModel)tblUsuarios.getModel();
        llenarTabla();
    }
    
    private void llenarTabla() {
        String estado;
        int count = 0;
        tableData = Usuarios.visualizarUsuarios();
        for(Usuarios usuario:tableData) {
            if(usuario.isEstadoUsuario()){
                estado = "Activo";
            }else {
                estado = "Archivado";
            }
            if(count != 0) {
                modeloTabla.addRow(new Object[] {
                    usuario.getIdUsuario(),
                    usuario.getNombres(),
                    usuario.getApellidos(),
                    usuario.getUsuario(),
                    usuario.getCargo(),
                    usuario.getRol(),
                    estado
                });
            }
            count = 1;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(916, 629));
        setMinimumSize(new java.awt.Dimension(916, 629));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Usuario", "Cargo", "Rol", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblUsuariosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblUsuarios.getColumnModel().getColumn(0).setCellRenderer(render);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblUsuarios.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblUsuarios.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblUsuariosMouseClicked
        int filaSeleccionada = tblUsuarios.getSelectedRow();
        boolean isDifferentUser = tblUsuarios.getValueAt(filaSeleccionada, 6).equals("Archivado");
        boolean isValidRow = filaSeleccionada != -1;
        
        if(isValidRow && !isDifferentUser) {
            int id = Integer.valueOf(tblUsuarios.getValueAt(filaSeleccionada, 0).toString());
            String nombre = tblUsuarios.getValueAt(filaSeleccionada, 1).toString();
            String apellido = tblUsuarios.getValueAt(filaSeleccionada, 2).toString();
            String usuario = tblUsuarios.getValueAt(filaSeleccionada, 3).toString();
            String contrasenia = Usuarios.getContrasenia(id);
            String cargo = tblUsuarios.getValueAt(filaSeleccionada, 4).toString();
            String rol = tblUsuarios.getValueAt(filaSeleccionada, 5).toString();
            String estado = tblUsuarios.getValueAt(filaSeleccionada, 6).toString();
            boolean estadoBool = (estado.equals("Activo"));
            System.out.println(estadoBool);
            usuariosVista.abrirEditar(id, nombre, apellido, usuario, contrasenia, rol, cargo, estadoBool);
        }else {
            JOptionPane.showMessageDialog(this, "Los usuarios archivados solo pueden ser restaurados por el administrador del sistema", "Alerta",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_tblUsuariosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
