/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

import java.util.List;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import servicios.Cliente;

/**
 *
 * @author recab
 */
public class TablaClientes extends javax.swing.JInternalFrame {
    DefaultTableModel modeloTabla;
    List<Cliente> tableData;
    DefaultTableCellRenderer render = new DefaultTableCellRenderer();
    private ClientesVista clientesVista;
    /**
     * Creates new form TablaClientes
     */
    public TablaClientes(ClientesVista clientesVista) {
        initComponents();
        this.clientesVista = clientesVista;
        
        render.setHorizontalAlignment(JLabel.CENTER);
        modeloTabla = (DefaultTableModel)tblClientes.getModel();
        llenarTabla();
    }
    private void llenarTabla() {
        tableData = Cliente.visualizarClientes();
        for(Cliente cliente:tableData) { 
            modeloTabla.addRow(new Object[] {
                cliente.getIdCliente(),
                cliente.getDocIdent(),
                cliente.getNit(),
                cliente.getNombre(),
                cliente.getApellido(),
                cliente.getDireccion(),
                cliente.getCorreo(),
                cliente.getTelefono(),
                cliente.getFecha(),

            });
        }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblClientes = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(916, 629));
        setMinimumSize(new java.awt.Dimension(916, 629));
        setPreferredSize(new java.awt.Dimension(916, 629));

        tblClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Documento", "Nit", "Nombre", "Apellido", "Direccion", "Correo", "Telefono", "Fecha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblClientes.getTableHeader().setReorderingAllowed(false);
        tblClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblClientes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 892, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 587, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblClientesMouseClicked
        // TODO add your handling code here:
                int filaSeleccionada = tblClientes.getSelectedRow();
        if(filaSeleccionada != -1) {
            int id = Integer.valueOf(tblClientes.getValueAt(filaSeleccionada, 0).toString());
            int doc = Integer.valueOf(tblClientes.getValueAt(filaSeleccionada, 1).toString());
            String nit = tblClientes.getValueAt(filaSeleccionada, 2).toString();
            String nombre = tblClientes.getValueAt(filaSeleccionada, 3).toString();
            String apellido = tblClientes.getValueAt(filaSeleccionada, 4).toString();
            String direccion = tblClientes.getValueAt(filaSeleccionada, 5).toString();
            String correo = tblClientes.getValueAt(filaSeleccionada, 6).toString();
            String telefono = tblClientes.getValueAt(filaSeleccionada, 7).toString();
            String fecha = tblClientes.getValueAt(filaSeleccionada, 8).toString();
            clientesVista.abrirEditar(id, doc, nit, nombre, apellido, direccion, correo, telefono, fecha);

        }
    }//GEN-LAST:event_tblClientesMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblClientes;
    // End of variables declaration//GEN-END:variables
}
