/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package vistas;

/**
 *
 * @author Daniel Aldana
 */

import javax.swing.table.DefaultTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import servicios.Usuarios;

public class TablaUsuarios extends javax.swing.JInternalFrame {
    
    DefaultTableModel modeloTabla;
    ResultSet tableData;

    /**
     * Creates new form TablaUsuarios
     */
    public TablaUsuarios() {
        initComponents();
        
        modeloTabla = (DefaultTableModel)tblUsuarios.getModel();
        llenarTabla();
    }
    
    private void llenarTabla() {
        String estado;
        tableData = Usuarios.visualizarUsuarios();
        try {
            while(tableData.next()) {
                if(tableData.getBoolean("estado_usuario")) {
                    estado = "Activo";
                }else {
                    estado = "Archivado";
                }
                modeloTabla.addRow(new Object[] {
                    tableData.getString("id_usuario"),
                    tableData.getString("nombre_usuario"),
                    tableData.getString("apellido_usuario"),
                    tableData.getString("usuario"),
                    tableData.getString("cargo_usuario_id"),
                    tableData.getString("rol_usuario_id"),
                    estado
                });
            }
        }catch(SQLException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblUsuarios = new javax.swing.JTable();

        setMaximumSize(new java.awt.Dimension(916, 629));
        setMinimumSize(new java.awt.Dimension(916, 629));

        tblUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Usuario", "Cargo", "Rol", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblUsuarios);
        if (tblUsuarios.getColumnModel().getColumnCount() > 0) {
            tblUsuarios.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblUsuarios.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblUsuarios.getColumnModel().getColumn(4).setPreferredWidth(30);
            tblUsuarios.getColumnModel().getColumn(5).setPreferredWidth(20);
            tblUsuarios.getColumnModel().getColumn(6).setPreferredWidth(20);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblUsuarios;
    // End of variables declaration//GEN-END:variables
}
